image:
  file: img-dev.dockerfile

ports:
- port: 8080
  onOpen: open-preview

tasks:

- init: |
    ./mvnw package
  command: |
    java -jar target/*.jar

- name: gcloud
  command: |
    GCLOUD_ADC_PATH="/home/gitpod/.config/gcloud/application_default_credentials.json"
    if [ -z "$GCP_ADC_FILE" ]; then
      echo "GCP_ADC_FILE not set, doing nothing."
    else
      echo "$GCP_ADC_FILE" > "$GCLOUD_ADC_PATH"
      echo "Set GOOGLE_APPLICATION_CREDENTIALS value based on contents from GCP_ADC_FILE"
      export GOOGLE_APPLICATION_CREDENTIALS="$GCLOUD_ADC_PATH"
    fi
    gcloud container clusters get-credentials moritz-pet-clinic --zone us-west1-b --project gke-playground-191013
