image:
  file: img-dev.dockerfile

ports:
- port: 8080
  onOpen: open-preview

tasks:

- init: |
    ./mvnw package
  command: |
    java -jar target/*.jar

- name: gcloud
  command: |
    echo $GCP_ACCOUNT > ~/account.json
    gcloud auth activate-service-account playground --key-file=~/account.json
    gcloud config set project gke-playground-191013
    gcloud container clusters get-credentials moritz-pet-clinic --zone us-west1-b --project gke-playground-191013
