image:
  file: img-dev.dockerfile

vscode:
  extensions:
    - Pivotal.vscode-spring-boot@1.11.0:gKokcVIlbvXM5pr9HCsGiA==
    - vscjava.vscode-spring-initializr@0.4.6:WOgtgIwX3Ngy4pM9ArXjCQ==
    - vscjava.vscode-spring-boot-dashboard@0.1.6:/G6fobfzYSrYZdNU7UB78g==
    - googlecloudtools.cloudcode@0.0.12:aImviY7NjOmGuXuyoD+uxQ==

ports:
- port: 8080
  onOpen: open-preview
- port: 2375
  onOpen: ignore

tasks:

- init: |
    ./mvnw package
  command: |
    java -jar target/*.jar

- name: gcloud
  command: |
    echo $GCP_ACCOUNT > /home/gitpod/account.json
    gcloud auth activate-service-account --key-file=/home/gitpod/account.json
    rm /home/gitpod/account.json
    gcloud config set project gke-playground-191013
    gcloud container clusters get-credentials moritz-pet-clinic --zone us-west1-b --project gke-playground-191013
    kubectl apply -f docker-engine.k8s.yaml
    kubectl port-forward deployment/docker-engine 2375:2375 &
