apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-engine
  labels:
    app: docker-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-engine
  template:
    metadata:
      labels:
        app: docker-engine
    spec:
      containers:
#  - name: my-main-container
#    env:
#    - name: DOCKER_HOST
#      value: tcp://localhost:2375
      - name: dind
        image: docker:dind
        securityContext:
          privileged: true
        #env:
        #- name: DOCKER_TLS_VERIFY
        #  value: "0"
        ports:
        - containerPort: 2376
        volumeMounts:
          - name: dind-storage
            mountPath: /var/lib/docker
      volumes:
      - name: dind-storage
        emptyDir: {}
